# Generated by Django 2.0.7 on 2019-08-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='payment',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
