# Generated by Django 2.0.7 on 2019-08-23 16:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0002_auto_20190822_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
