# Generated by Django 2.0.7 on 2019-08-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0004_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadline',
            name='deadline',
            field=models.CharField(max_length=20),
        ),
    ]
