# Generated by Django 2.0.7 on 2019-09-01 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0007_auto_20190901_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.DeleteModel(
            name='subcategory',
        ),
    ]
