# Generated by Django 2.0.7 on 2019-09-01 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0009_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadline',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jobs.subcategory'),
        ),
    ]
