# Generated by Django 2.0.7 on 2019-09-17 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0014_order_workload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workload',
            name='project_id',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Workload',
        ),
    ]
