# Generated by Django 2.0.7 on 2019-09-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0017_auto_20190917_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
