# Generated by Django 2.0.7 on 2019-09-18 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0018_order_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=50)),
                ('stage', models.IntegerField()),
                ('status', models.CharField(default='Waiting', max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jobs.subcategory')),
            ],
        ),
    ]
