# Generated by Django 2.2.5 on 2019-09-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0020_order_abbr'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
