# Generated by Django 2.2.5 on 2019-10-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0021_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='min_date',
            field=models.IntegerField(default=3),
        ),
    ]
