# Generated by Django 2.2.5 on 2019-10-20 10:34

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0023_auto_20191020_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='cost_per_day',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('500.0'), default_currency='NGN', max_digits=8),
        ),
    ]
