# Generated by Django 2.2.5 on 2019-10-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0025_customize'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='quote',
            field=models.BooleanField(default=False),
        ),
    ]
