# Generated by Django 2.2.5 on 2019-11-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0027_auto_20191110_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='max_date',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='min_date',
            field=models.IntegerField(default=3),
        ),
    ]
