# Generated by Django 2.2.5 on 2019-11-17 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0030_orderpackage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderpackage',
            old_name='packageAmount',
            new_name='package_amount',
        ),
        migrations.RenameField(
            model_name='orderpackage',
            old_name='packageAmount_currency',
            new_name='package_amount_currency',
        ),
        migrations.RenameField(
            model_name='orderpackage',
            old_name='packageName',
            new_name='package_name',
        ),
    ]
