# Generated by Django 2.0.7 on 2019-08-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='about',
            field=models.TextField(default='info about category'),
        ),
    ]
