# Generated by Django 2.1.5 on 2019-09-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_customuser_referal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='referal_point',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
