# Generated by Django 2.1.5 on 2019-09-21 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_customuser_referal_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='Candidate',
        ),
    ]
