# Generated by Django 2.2.5 on 2019-10-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_auto_20190930_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default='empty.png', upload_to='profile'),
        ),
    ]
