# Generated by Django 2.2.5 on 2019-10-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='image',
            field=models.ImageField(default='me.png', upload_to='categories/'),
        ),
    ]
