# Generated by Django 2.2.5 on 2019-10-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0011_auto_20191027_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='terms',
            name='name',
            field=models.CharField(default='Terms and condition', max_length=50),
        ),
    ]
