# Generated by Django 2.2.5 on 2019-11-10 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0013_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default='profile/logo.png', upload_to='profile'),
        ),
    ]
