# Generated by Django 2.2.5 on 2019-11-10 10:41

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20191110_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='customers/')),
                ('company', models.CharField(blank=True, max_length=50)),
                ('testimony', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
